export const ENV_VARS = {
    PROJECT_ID: process.env.NEXT_PUBLIC_PROJECT_ID!,
    API_ENDPOINT: process.env.NEXT_PUBLIC_API_ENDPOINT!,
    DATABASE_ID: process.env.NEXT_PUBLIC_DATABASE_ID!,
    LEADS_TABLE_ID: process.env.NEXT_PUBLIC_LEADS_TABLE_ID!,
    TAGS_TABLE_ID: process.env.NEXT_PUBLIC_TAGS_TABLE_ID!,
    LEAD_TAGS_TABLE_ID: process.env.NEXT_PUBLIC_LEAD_TAGS_TABLE_ID!,
    NOTES_TABLE_ID: process.env.NEXT_PUBLIC_NOTES_TABLE_ID!,
    FOLLOW_UP_TABLE_ID: process.env.NEXT_PUBLIC_FOLLOW_UP_TABLE_ID!,
};